### ISSUE TITLE
Dodanie modułu komunikacji z serwerem ExpogerSrv.

### ISSUE THREAD

**Issue by JaroslawParadysz** [JaroslawParadysz/WorkSpaceExpogerUI#11]
story points: 3
Jako deweloper chcę zaimplementować moduł odpowiedzialny za komunikację z serwerem aplikacji.

Pozwoli to na wymianę danych aplikacji UI z aplikacją serwerową. Komunikacja będzie się odbywac się REST API.
Moduł powinien być w miarę możliwości uniwersalny(przez użycie np. generyczności), umożliwiając pobrania/wysłanie, deserializację/serializację danych.
Podstawowe API:

List stanowisk
URI: "api/commercialplaces/list"
Metoda: Post
Request json"
{"Count":""}
Response json:
{[{"Id": "", "Surface", "Price":"", "Timetable":[{Id:"","Start":"yyyy-MM-ddThh:mm:ss","End":"yyyy-MM-ddThh:mm:ss"}]}]}

Rezerwacja miejsca targowego:
URI: "api/reservations/acceptance"
{"CommercialPlaceId":"", "Start":"yyyy-MM-ddThh:mm:ss", End:""}

Akceptacja:
Dane związane ze stanowiskami targowymi, terminarzami, składaniem rezerwacji na stanowisko, sa pobierane przy użyciu implementowanego moduło.

**Comment by Reagnar** [comment]
Ok
