### ISSUE TITLE
Dodanie widoku tworzenia konta użytkownika.

### ISSUE THREAD

**Issue by JaroslawParadysz** [JaroslawParadysz/WorkSpaceExpogerUI#6]
story points: 3
Jako deweloper chcę utworzyć widok umożliwiający wprowadzeniewymaganych danych do utworzenia konta użytkownika w systemie.

Pozwoli to na dalszą implementację funkcjonalności użytkowników aplikacji.

Akceptacja:
Widok zawiera textbox'y:
-imie
-nazwisko
-nazwa użytkownika
-hasło
-powtórzone hasło
Widok powinie zawierać przycisk SUBMIT
Przekazane dane powinny być walidowane w celu iniknięcią SQLInjection.

**Comment by Reagnar** [comment]
Ok
