### ISSUE TITLE
Integracja z serwerową funkcjonalnością logowania się użytkownika do aplikacji.

### ISSUE THREAD

**Issue by JaroslawParadysz** [JaroslawParadysz/WorkSpaceExpogerUI#9]
story points: 3
Jako deweloper chcę zintegrować aplikację UI  z serwerem w ramach funkcjonalności logowania się użytkownika do aplikacji.

Umożliwi to zalogowanie się użytkownika do systemu.
URI do ustalenia, wstępnie "users/auth".
Hasło nie jest szyfrowane.
Wstępny format wymieniancy wiadomości z serwerem:
Request json:
 {"Username":"","Password":"", "Rememberme":"false}
Response json:
Do ustalenia.

Akceptacja:
Wprowadzone dane w ekranie logowania(hasło, nazwa użytkownika), są wstępnie walidowane(uniknięcie SQLInjection), oraz są przesyłane na serwer przez REST API metodą Post, w formie json. Widok wyświetla zwrócone informacje przez serwer, informujący tym samym użytkownika o błędzie, lub pomyślnym zalogowaniu się do systemu.

**Comment by Reagnar** [comment]
Ok
